apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    name: client
spec:
  containers:
  - name: client
    image: design-studio-client:latest
    imagePullPolicy: Never
    resources:
      limits:
        memory: "1280Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
