apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    name: client
spec:
  containers:
  - name: client
    image: client-image-v1
    imagePullPolicy: Never
    resources:
      limits:
        memory: "1400Mi"
        cpu: "700m"
    ports:
      - containerPort: 3000
