version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: design-studio-server
    container_name: design-studio-server
    command: /app/node_modules/.bin/nodemon app.js
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: design-studio-client
    container_name: design-studio-client
    command: npm start
    volumes:
      - ./client/:/frontend
      - /frontend/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local