apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo
#   #annotations: 
#    #pv.beta.kubernetes.io/gid: "1000"
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#   - ReadWriteOnce
#   azureFile:
#     secretName: storage-connection
#     secretNamespace: mongo
#     shareName: {{ .Values.mongo.azurefileshare }}
#     readOnly: false
#   claimRef:
#     name: mongo-pvc
#     kind: PersistenVolumeClaim
#     namespace: mongo
#   persistentVolumeReclaimPolicy: Retain