name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull nevdread/client:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f client-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:80 --name client-container nevdread/client

     


      