name: CDK Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Kubernetes deployment client
      run: kubectl apply -f ./deployment/client/  
    - name: Kubernetes deployment server
      run: kubectl apply -f ./deployment/server/ 
    

     


      